-- MySQL Script generated by MySQL Workbench
-- Thu Sep 20 16:37:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`disability`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`disability` ;

CREATE TABLE IF NOT EXISTS `mydb`.`disability` (
  `id_disability` BIGINT(20) UNSIGNED NOT NULL,
  `disability_degree` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_disability`),
  UNIQUE INDEX `disability_degree_UNIQUE` (`disability_degree` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`city` ;

CREATE TABLE IF NOT EXISTS `mydb`.`city` (
  `id_city` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_city`),
  UNIQUE INDEX `id_city_UNIQUE` (`id_city` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`merital_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`merital_status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`merital_status` (
  `id_merital_status` BIGINT(20) UNSIGNED NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_merital_status`),
  UNIQUE INDEX `status_UNIQUE` (`status` ASC),
  UNIQUE INDEX `id_merital_status_UNIQUE` (`id_merital_status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`citizenship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`citizenship` ;

CREATE TABLE IF NOT EXISTS `mydb`.`citizenship` (
  `id_citizenship` BIGINT(20) UNSIGNED NOT NULL,
  `citizenship` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_citizenship`),
  UNIQUE INDEX `citizenship_UNIQUE` (`citizenship` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id_client` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `middlename` VARCHAR(50) NOT NULL,
  `birthday` DATE NOT NULL,
  `passport_series` VARCHAR(5) NOT NULL,
  `passport_number` VARCHAR(10) NOT NULL,
  `issued_by` VARCHAR(100) NOT NULL,
  `issue_date` DATE NOT NULL,
  `ident_number` VARCHAR(30) NOT NULL,
  `birthday_place` VARCHAR(50) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `home_telephone` VARCHAR(20) NULL,
  `mobile_phone` VARCHAR(20) NULL,
  `email` VARCHAR(50) NULL,
  `workplace` VARCHAR(50) NULL,
  `position` VARCHAR(30) NULL,
  `pensioner` TINYINT(1) NOT NULL,
  `salary` DECIMAL(15,3) NULL,
  `militarity` TINYINT(1) NOT NULL,
  `id_disability` BIGINT(20) UNSIGNED NOT NULL,
  `id_city` BIGINT(20) UNSIGNED NOT NULL,
  `id_merital_status` BIGINT(20) UNSIGNED NOT NULL,
  `id_citizenship` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `id_client_UNIQUE` (`id_client` ASC),
  INDEX `fk_client_disability1_idx` (`id_disability` ASC),
  INDEX `fk_client_city1_idx` (`id_city` ASC),
  INDEX `fk_client_merital_status1_idx` (`id_merital_status` ASC),
  INDEX `fk_client_citizenship1_idx` (`id_citizenship` ASC),
  CONSTRAINT `fk_client_disability1`
    FOREIGN KEY (`id_disability`)
    REFERENCES `mydb`.`disability` (`id_disability`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_city1`
    FOREIGN KEY (`id_city`)
    REFERENCES `mydb`.`city` (`id_city`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_merital_status1`
    FOREIGN KEY (`id_merital_status`)
    REFERENCES `mydb`.`merital_status` (`id_merital_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_citizenship1`
    FOREIGN KEY (`id_citizenship`)
    REFERENCES `mydb`.`citizenship` (`id_citizenship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client_city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`client_city` ;

CREATE TABLE IF NOT EXISTS `mydb`.`client_city` (
  `id_client` BIGINT(20) UNSIGNED NOT NULL,
  `id_city` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_city`, `id_client`),
  INDEX `fk_city_cient_client_idx` (`id_client` ASC),
  INDEX `fk_city_cient_city1_idx` (`id_city` ASC),
  CONSTRAINT `fk_city_cient_client`
    FOREIGN KEY (`id_client`)
    REFERENCES `mydb`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_city_cient_city1`
    FOREIGN KEY (`id_city`)
    REFERENCES `mydb`.`city` (`id_city`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client_registration_city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`client_registration_city` ;

CREATE TABLE IF NOT EXISTS `mydb`.`client_registration_city` (
  `client_id_client` BIGINT(20) UNSIGNED NOT NULL,
  `city_id_city` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`client_id_client`, `city_id_city`),
  INDEX `fk_client_registration_city_city1_idx` (`city_id_city` ASC),
  CONSTRAINT `fk_client_registration_city_client1`
    FOREIGN KEY (`client_id_client`)
    REFERENCES `mydb`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_registration_city_city1`
    FOREIGN KEY (`city_id_city`)
    REFERENCES `mydb`.`city` (`id_city`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client_disability`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`client_disability` ;

CREATE TABLE IF NOT EXISTS `mydb`.`client_disability` (
  `id_disability` BIGINT(20) UNSIGNED NOT NULL,
  `id_client` BIGINT(20) UNSIGNED NOT NULL,
  INDEX `fk_client_disability_disability1_idx` (`id_disability` ASC),
  INDEX `fk_client_disability_client1_idx` (`id_client` ASC),
  PRIMARY KEY (`id_disability`, `id_client`),
  CONSTRAINT `fk_client_disability_disability1`
    FOREIGN KEY (`id_disability`)
    REFERENCES `mydb`.`disability` (`id_disability`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_disability_client1`
    FOREIGN KEY (`id_client`)
    REFERENCES `mydb`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client_merital_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`client_merital_status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`client_merital_status` (
  `id_merital_status` BIGINT(20) UNSIGNED NOT NULL,
  `id_client` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_merital_status`, `id_client`),
  INDEX `fk_table1_client1_idx` (`id_client` ASC),
  CONSTRAINT `fk_table1_merital_status1`
    FOREIGN KEY (`id_merital_status`)
    REFERENCES `mydb`.`merital_status` (`id_merital_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_client1`
    FOREIGN KEY (`id_client`)
    REFERENCES `mydb`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client_citizenship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`client_citizenship` ;

CREATE TABLE IF NOT EXISTS `mydb`.`client_citizenship` (
  `id_client` BIGINT(20) UNSIGNED NOT NULL,
  `id_citizenship` BIGINT(20) UNSIGNED NOT NULL,
  INDEX `fk_client_citizenship_client1_idx` (`id_client` ASC),
  INDEX `fk_client_citizenship_citizenship1_idx` (`id_citizenship` ASC),
  PRIMARY KEY (`id_client`, `id_citizenship`),
  CONSTRAINT `fk_client_citizenship_client1`
    FOREIGN KEY (`id_client`)
    REFERENCES `mydb`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_citizenship_citizenship1`
    FOREIGN KEY (`id_citizenship`)
    REFERENCES `mydb`.`citizenship` (`id_citizenship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
